# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 59) do

  create_table "addresses", :force => true do |t|
    t.column "entity_id",  :integer,               :default => 0,  :null => false
    t.column "label",      :string,                :default => "", :null => false
    t.column "line_1",     :string
    t.column "line_2",     :string
    t.column "city",       :string
    t.column "state",      :string
    t.column "zip",        :string,   :limit => 5
    t.column "zip_4",      :string,   :limit => 4
    t.column "valid_from", :date
    t.column "valid_to",   :date
    t.column "created_by", :integer
    t.column "updated_by", :integer
    t.column "created_at", :datetime,                              :null => false
    t.column "updated_at", :datetime,                              :null => false
  end

  add_index "addresses", ["entity_id"], :name => "addresses_entity_id_index"

  create_table "campaign_events", :force => true do |t|
    t.column "campaign_id",            :integer
    t.column "name",                   :string
    t.column "start_time",             :datetime
    t.column "hidden",                 :boolean,               :default => false
    t.column "created_at",             :datetime
    t.column "updated_at",             :datetime
    t.column "end_time",               :datetime
    t.column "website",                :string
    t.column "addr_line1",             :string
    t.column "addr_line2",             :string
    t.column "addr_city",              :string
    t.column "addr_state",             :string
    t.column "addr_zip",               :string,   :limit => 5
    t.column "location_name",          :string
    t.column "goal",                   :float
    t.column "recipient_committee_id", :integer
  end

  add_index "campaign_events", ["campaign_id"], :name => "campaign_events_campaign_id_index"

  create_table "campaign_user_roles", :force => true do |t|
    t.column "user_id",     :integer, :default => 0,     :null => false
    t.column "role_id",     :integer, :default => 0,     :null => false
    t.column "campaign_id", :integer, :default => 0,     :null => false
    t.column "created_by",  :integer
    t.column "updated_by",  :integer
    t.column "api_token",   :string
    t.column "financial",   :boolean, :default => false
  end

  add_index "campaign_user_roles", ["user_id"], :name => "campaign_user_roles_user_id_index"
  add_index "campaign_user_roles", ["user_id", "campaign_id"], :name => "user_campaign_index"

  create_table "campaigns", :force => true do |t|
    t.column "name",        :string
    t.column "from_emails", :text
  end

  create_table "cart_items", :force => true do |t|
    t.column "user_id",   :integer
    t.column "entity_id", :integer
  end

  add_index "cart_items", ["user_id"], :name => "cart_items_user_id_index"

  create_table "committees", :force => true do |t|
    t.column "campaign_id",               :integer
    t.column "name",                      :string
    t.column "treasurer_id",              :integer
    t.column "treasurer_api_url",         :string
    t.column "treasurer_entity_show_url", :string
  end

  add_index "committees", ["campaign_id"], :name => "committees_campaign_id_index"

  create_table "contact_events", :force => true do |t|
    t.column "entity_id",           :integer
    t.column "contact_text_id",     :integer
    t.column "when_contact",        :datetime
    t.column "initiated_by",        :string
    t.column "interaction",         :boolean,  :default => false
    t.column "form",                :string
    t.column "will_contribute",     :boolean,  :default => false
    t.column "will_volunteer",      :boolean,  :default => false
    t.column "how_volunteer",       :string
    t.column "when_volunteer",      :date
    t.column "when_volunteer_text", :string
    t.column "yard_sign",           :boolean,  :default => false
    t.column "memo",                :text
    t.column "requires_followup",   :boolean,  :default => false
    t.column "future_contact_date", :date
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
    t.column "campaign_id",         :integer
    t.column "campaign_event_id",   :integer
    t.column "message_id",          :string
    t.column "status",              :string
    t.column "pledge_value",        :float
  end

  add_index "contact_events", ["entity_id"], :name => "contact_events_entity_id_index"
  add_index "contact_events", ["contact_text_id"], :name => "contact_events_contact_text_id_index"
  add_index "contact_events", ["campaign_event_id"], :name => "contact_events_campaign_event_id_index"

  create_table "contact_texts", :force => true do |t|
    t.column "stylesheet_id",     :integer
    t.column "label",             :string
    t.column "type",              :string
    t.column "sender",            :string
    t.column "subject",           :string
    t.column "text",              :text
    t.column "complete",          :boolean,  :default => false
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
    t.column "campaign_id",       :integer
    t.column "formatted_text",    :text
    t.column "campaign_event_id", :integer
  end

  add_index "contact_texts", ["campaign_id"], :name => "contact_texts_campaign_id_index"

  create_table "contributions", :force => true do |t|
    t.column "entity_id",              :integer
    t.column "amount",                 :float
    t.column "date",                   :datetime
    t.column "created_at",             :datetime, :null => false
    t.column "updated_at",             :datetime, :null => false
    t.column "recipient",              :string
    t.column "campaign_event_id",      :integer
    t.column "recipient_committee_id", :integer
    t.column "import_transaction_id",  :string
  end

  add_index "contributions", ["entity_id"], :name => "contributions_entity_id_index"

  create_table "custom_field_values", :force => true do |t|
    t.column "entity_id",       :integer
    t.column "custom_field_id", :integer
    t.column "value",           :string
    t.column "created_at",      :datetime, :null => false
    t.column "updated_at",      :datetime, :null => false
  end

  add_index "custom_field_values", ["entity_id"], :name => "custom_field_values_entity_id_index"
  add_index "custom_field_values", ["custom_field_id"], :name => "custom_field_values_custom_field_id_index"

  create_table "custom_fields", :force => true do |t|
    t.column "campaign_id",    :integer
    t.column "name",           :string
    t.column "field_type",     :string
    t.column "select_options", :text
    t.column "hidden",         :boolean
    t.column "created_at",     :datetime, :null => false
    t.column "updated_at",     :datetime, :null => false
    t.column "display_order",  :integer
  end

  add_index "custom_fields", ["campaign_id"], :name => "custom_fields_campaign_id_index"

  create_table "email_addresses", :force => true do |t|
    t.column "entity_id",  :integer
    t.column "label",      :string
    t.column "address",    :string
    t.column "invalid",    :boolean,  :default => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "created_by", :integer
    t.column "updated_by", :integer
  end

  add_index "email_addresses", ["entity_id"], :name => "email_addresses_entity_id_index"

  create_table "entities", :force => true do |t|
    t.column "type",                  :string,   :limit => 40, :default => "", :null => false
    t.column "campaign_id",           :integer,                :default => 0,  :null => false
    t.column "household_id",          :integer
    t.column "field_id",              :integer
    t.column "name",                  :string,                 :default => "", :null => false
    t.column "title",                 :string
    t.column "first_name",            :string
    t.column "middle_name",           :string
    t.column "last_name",             :string
    t.column "name_suffix",           :string
    t.column "nickname",              :string
    t.column "voter_ID",              :string
    t.column "precinct",              :string
    t.column "languages",             :string
    t.column "skills",                :text
    t.column "occupation",            :string
    t.column "employer",              :string
    t.column "time_to_reach",         :string
    t.column "receive_email",         :boolean
    t.column "receive_phone",         :boolean
    t.column "federal_ID",            :string,   :limit => 20
    t.column "state_ID",              :string,   :limit => 20
    t.column "party",                 :boolean
    t.column "created_by",            :integer
    t.column "updated_by",            :integer
    t.column "created_at",            :datetime,                               :null => false
    t.column "updated_at",            :datetime,                               :null => false
    t.column "phones",                :text
    t.column "primary_phone",         :string,   :limit => 40
    t.column "faxes",                 :text
    t.column "primary_fax",           :string,   :limit => 40
    t.column "emails",                :text
    t.column "primary_email_label",   :string
    t.column "registered_party",      :string,   :limit => 40
    t.column "birthdate",             :date
    t.column "primary_address_id",    :integer
    t.column "mailing_address_id",    :integer
    t.column "referred_by",           :string
    t.column "comments",              :text
    t.column "website",               :string
    t.column "delete_requested",      :boolean
    t.column "followup_required",     :boolean
    t.column "primary_email_id",      :integer
    t.column "import_contributor_id", :string
  end

  add_index "entities", ["type"], :name => "entities_type_index"
  add_index "entities", ["campaign_id"], :name => "entities_campaign_id_index"
  add_index "entities", ["household_id"], :name => "entities_household_id_index"
  add_index "entities", ["primary_address_id"], :name => "entities_primary_address_id_index"
  add_index "entities", ["primary_email_id"], :name => "entities_primary_email_id_index"

  create_table "entities_volunteer_tasks", :id => false, :force => true do |t|
    t.column "volunteer_task_id", :integer
    t.column "entity_id",         :integer
  end

  add_index "entities_volunteer_tasks", ["entity_id"], :name => "entities_volunteer_tasks_entity_id_index"
  add_index "entities_volunteer_tasks", ["volunteer_task_id"], :name => "entities_volunteer_tasks_volunteer_task_id_index"

  create_table "exported_files", :force => true do |t|
    t.column "filename",    :string,   :limit => 32
    t.column "campaign_id", :integer
    t.column "downloaded",  :boolean
    t.column "num_entries", :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "created_by",  :integer
    t.column "updated_by",  :integer
  end

  create_table "group_field_values", :force => true do |t|
    t.column "group_membership_id", :integer
    t.column "group_field_id",      :integer
    t.column "value",               :string
    t.column "created_at",          :datetime, :null => false
    t.column "updated_at",          :datetime
  end

  create_table "group_fields", :force => true do |t|
    t.column "group_id",       :integer
    t.column "name",           :string
    t.column "field_type",     :string
    t.column "created_at",     :datetime, :null => false
    t.column "updated_at",     :datetime
    t.column "select_options", :text
    t.column "hidden",         :boolean
  end

  create_table "group_memberships", :force => true do |t|
    t.column "group_id",   :integer
    t.column "entity_id",  :integer
    t.column "role",       :string
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime
  end

  add_index "group_memberships", ["entity_id"], :name => "group_memberships_entity_id_index"
  add_index "group_memberships", ["group_id"], :name => "group_memberships_group_id_index"

  create_table "groups", :force => true do |t|
    t.column "name",        :string
    t.column "created_at",  :datetime, :null => false
    t.column "updated_at",  :datetime
    t.column "campaign_id", :integer,  :null => false
  end

  add_index "groups", ["campaign_id"], :name => "groups_campaign_id_index"

  create_table "households", :force => true do |t|
    t.column "campaign_id", :integer
  end

  create_table "prohibited_actions", :force => true do |t|
    t.column "name", :string, :limit => 40, :default => "", :null => false
  end

  create_table "prohibited_actions_roles", :id => false, :force => true do |t|
    t.column "role_id",              :integer, :default => 0, :null => false
    t.column "prohibited_action_id", :integer, :default => 0, :null => false
  end

  create_table "prohibited_controllers", :force => true do |t|
    t.column "name", :string, :limit => 40, :default => "", :null => false
  end

  create_table "prohibited_controllers_roles", :id => false, :force => true do |t|
    t.column "role_id",                  :integer, :default => 0, :null => false
    t.column "prohibited_controller_id", :integer, :default => 0, :null => false
  end

  create_table "prohibitions", :force => true do |t|
    t.column "name", :string, :limit => 40, :default => "", :null => false
  end

  create_table "prohibitions_roles", :id => false, :force => true do |t|
    t.column "role_id",        :integer, :default => 0, :null => false
    t.column "prohibition_id", :integer, :default => 0, :null => false
  end

  create_table "roles", :force => true do |t|
    t.column "name", :string,  :limit => 40, :default => "", :null => false
    t.column "rank", :integer,               :default => 1,  :null => false
  end

  create_table "rsvps", :force => true do |t|
    t.column "entity_id",         :integer
    t.column "campaign_event_id", :integer
    t.column "response",          :string
    t.column "invited",           :boolean, :default => false
    t.column "attended",          :boolean, :default => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "stylesheets", :force => true do |t|
    t.column "name",          :string,   :default => "",          :null => false
    t.column "side_bg",       :string,   :default => "465F7E"
    t.column "title_bg",      :string,   :default => "C0D9FF"
    t.column "body_bg",       :string,   :default => "FFFFFF"
    t.column "h1_color",      :string,   :default => "000000"
    t.column "h2_color",      :string,   :default => "000000"
    t.column "h3_color",      :string,   :default => "000000"
    t.column "h4_color",      :string,   :default => "000000"
    t.column "h5_color",      :string,   :default => "000000"
    t.column "p_color",       :string,   :default => "000000"
    t.column "a_color",       :string,   :default => "000099"
    t.column "strong_color",  :string,   :default => "000000"
    t.column "h1_size",       :string,   :default => "24"
    t.column "h2_size",       :string,   :default => "18"
    t.column "h3_size",       :string,   :default => "14"
    t.column "h4_size",       :string,   :default => "12"
    t.column "h5_size",       :string,   :default => "10"
    t.column "p_size",        :string,   :default => "12"
    t.column "h1_serif",      :boolean,  :default => false
    t.column "h2_serif",      :boolean,  :default => false
    t.column "h3_serif",      :boolean,  :default => false
    t.column "h4_serif",      :boolean,  :default => false
    t.column "h5_serif",      :boolean,  :default => false
    t.column "p_serif",       :boolean,  :default => false
    t.column "h1_align",      :string,   :default => "left"
    t.column "h2_align",      :string,   :default => "left"
    t.column "h3_align",      :string,   :default => "left"
    t.column "h4_align",      :string,   :default => "left"
    t.column "h5_align",      :string,   :default => "left"
    t.column "p_justify",     :boolean,  :default => false
    t.column "h1_weight",     :string,   :default => "bold"
    t.column "h2_weight",     :string,   :default => "bold"
    t.column "h3_weight",     :string,   :default => "bold"
    t.column "h4_weight",     :string,   :default => "bold"
    t.column "h5_weight",     :string,   :default => "bold"
    t.column "em_weight",     :string,   :default => "normal"
    t.column "strong_weight", :string,   :default => "bold"
    t.column "em_style",      :string,   :default => "italic"
    t.column "strong_style",  :string,   :default => "normal"
    t.column "a_decoration",  :string,   :default => "underline"
    t.column "ul_type",       :string,   :default => "disc"
    t.column "ol_type",       :string,   :default => "decimal"
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "hr_width",      :string,   :default => "80"
    t.column "hr_height",     :string,   :default => "3"
    t.column "hr_color",      :string,   :default => "CCCCCC"
    t.column "campaign_id",   :integer
  end

  add_index "stylesheets", ["campaign_id"], :name => "stylesheets_campaign_id_index"

  create_table "taggings", :force => true do |t|
    t.column "taggable_id",   :integer
    t.column "tag_id",        :integer
    t.column "taggable_type", :string
  end

  add_index "taggings", ["tag_id"], :name => "taggings_tag_id_index"
  add_index "taggings", ["taggable_id", "taggable_type"], :name => "taggable_index"

  create_table "tags", :force => true do |t|
    t.column "name",        :string
    t.column "campaign_id", :integer, :null => false
  end

  add_index "tags", ["campaign_id"], :name => "tags_campaign_id_index"

  create_table "treasurer_entities", :force => true do |t|
    t.column "committee_id", :integer
    t.column "entity_id",    :integer
    t.column "treasurer_id", :integer
  end

  add_index "treasurer_entities", ["entity_id"], :name => "treasurer_entities_entity_id_index"

  create_table "users", :force => true do |t|
    t.column "login",            :string,   :limit => 80, :default => "",    :null => false
    t.column "salted_password",  :string,   :limit => 40, :default => "",    :null => false
    t.column "email",            :string,   :limit => 60, :default => "",    :null => false
    t.column "firstname",        :string,   :limit => 40
    t.column "lastname",         :string,   :limit => 40
    t.column "salt",             :string,   :limit => 40, :default => "",    :null => false
    t.column "verified",         :boolean,                :default => false
    t.column "security_token",   :string,   :limit => 40
    t.column "token_expiry",     :datetime
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "logged_in_at",     :datetime
    t.column "delete_after",     :datetime
    t.column "deleted",          :boolean,                :default => false
    t.column "created_by",       :integer
    t.column "treasurer_info",   :text
    t.column "current_campaign", :integer
  end

  create_table "volunteer_events", :force => true do |t|
    t.column "entity_id",         :integer
    t.column "volunteer_task_id", :integer
    t.column "comments",          :string
    t.column "start_time",        :datetime
    t.column "end_time",          :datetime
    t.column "duration",          :integer
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
  end

  add_index "volunteer_events", ["entity_id"], :name => "volunteer_events_entity_id_index"

  create_table "volunteer_tasks", :force => true do |t|
    t.column "name",          :string
    t.column "campaign_id",   :integer
    t.column "display_order", :integer
  end

  add_index "volunteer_tasks", ["campaign_id"], :name => "volunteer_tasks_campaign_id_index"

end
